#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x1B0 (0x5D8 - 0x428)
// WidgetBlueprintGeneratedClass WBP_CaptureReticle.WBP_CaptureReticle_C
class UWBP_CaptureReticle_C : public UPalUserWidget
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x428(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UCanvasPanel*                          Canvas_Root;                                       // 0x430(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalGetReticle_C*                  WBP_PalGetReticle;                                 // 0x438(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Reticle_Cancel_C*                 WBP_Reticle_Cancel;                                // 0x440(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class APalPlayerController*                  LocalController;                                   // 0x448(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<enum class EObjectTypeQuery>          TraceObjectTypeQueryArray;                         // 0x450(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	enum class EPalCaptureReticleSeqence         ReticleSeqence;                                    // 0x460(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_11EC[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TSoftObjectPtr<class APalMonsterCharacter>   NowTargetMonster;                                  // 0x468(0x30)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UPalLoadoutSelectorComponent*          LoadoutSelector;                                   // 0x498(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                         IsCaptureItemEquiped;                              // 0x4A0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_11EE[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TSoftObjectPtr<class ABP_ThrowWeaponBase_C>  LastEquipedWeapon;                                 // 0x4A8(0x30)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TMap<TSoftObjectPtr<class ABP_PalCaptureBodyBase_C>, class UWBP_PalGetReticle_C*> SecondStepWidgetMap;                               // 0x4D8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                         IsBonusEnabledWhenLastCheck;                       // 0x528(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         IsStopReticleUpdate;                               // 0x529(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_11F1[0x6];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       ReticleStopTimer;                                  // 0x530(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<TSoftObjectPtr<class APalCharacter>, class UWBP_CaptureFailedPercent_C*> FailedCaptureRateWidgetMap;                        // 0x538(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TMap<enum class E_PalCaptureSphereBouncedReason, enum class EPalLogType> BouncedBallLogTypeMap;                             // 0x588(0x50)(Edit, BlueprintVisible)

	static class UClass* StaticClass();
	static class UWBP_CaptureReticle_C* GetDefaultObj();

	void ShouldReticleDIsplay(bool* ShouldDisplay, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsAiming_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void DisplayCaptureFailedLog(class UPalIndividualCharacterHandle* TargetHandle, class UPalTutorialManager* CallFunc_GetTutorialManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_GetLevel_ReturnValue, const class FString& CallFunc_GetNickName_outName, int64 CallFunc_Conv_IntToInt64_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, class UPalLogManager* CallFunc_GetLogManager_ReturnValue, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_CreateLogText_outText, const struct FPalLogAdditionalData& K2Node_MakeStruct_PalLogAdditionalData, class FText CallFunc_Format_ReturnValue, const struct FGuid& CallFunc_AddLog_ReturnValue);
	void OnBouncedBall(enum class E_PalCaptureSphereBouncedReason ReasonType, class UPalIndividualCharacterHandle* TargetHandle, bool CallFunc_IsValid_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_GetLevel_ReturnValue, const class FString& CallFunc_GetNickName_outName, int64 CallFunc_Conv_IntToInt64_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, enum class EPalLogType CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FPalLogAdditionalData& K2Node_MakeStruct_PalLogAdditionalData, class FText CallFunc_CreateLogText_outText, class FText CallFunc_Format_ReturnValue, class UPalLogManager* CallFunc_GetLogManager_ReturnValue, const struct FGuid& CallFunc_AddLog_ReturnValue);
	void OnFailedPercentWidgetClear(class UWBP_CaptureFailedPercent_C* SelfWidget, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<TSoftObjectPtr<class APalCharacter>>& CallFunc_Map_Keys_Keys, int32 CallFunc_Array_Length_ReturnValue, TSoftObjectPtr<class APalCharacter> CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Map_Remove_ReturnValue, class UWBP_CaptureFailedPercent_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
	void UpdateFailedWidgets(double DeltaTime, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, TArray<TSoftObjectPtr<class APalCharacter>>& CallFunc_Map_Keys_Keys, int32 CallFunc_Array_Length_ReturnValue, TSoftObjectPtr<class APalCharacter> CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Map_Remove_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsValidSoftObjectReference_ReturnValue, const struct FVector2D& CallFunc_ProjectWorldLocationToWidgetPosition_ScreenPosition, bool CallFunc_ProjectWorldLocationToWidgetPosition_ReturnValue, const struct FVector2D& CallFunc_Add_Vector2DVector2D_ReturnValue, class UWBP_CaptureFailedPercent_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void CalcCaptureSuccessRate(TArray<double>& RateArray, double* SuccessRate, double TmpRate, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, double CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue);
	void IsBonusEnabled(const struct FVector& baseLocation, class APalMonsterCharacter* TargeActor, bool* Enabled, bool CallFunc_IsSneakAttackSuccessByLocation_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void Get_Display_Rate(class ABP_CapturePrism_C* CaptureItemActor, class APalMonsterCharacter* TargetMonster, double* Rate, bool* IsSneakBonus, class UPalCharacterManager* CallFunc_GetCharacterManager_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetCharacterParameterComponent_ReturnValue, int32 CallFunc_GetCaptureLevel_level, float CallFunc_Conv_IntToFloat_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue_1, const struct FPalInstanceID& CallFunc_GetIndividualIDByActor_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetIndividualHandle_ReturnValue, bool CallFunc_IsBonusEnabled_enabled, class UPalGameSetting* CallFunc_GetGameSetting_ReturnValue, float CallFunc_CalcCaptureRate_ReturnValue, TArray<float>& CallFunc_GetCalculatedCaptureRate_outCalculatedRateArray, int32 CallFunc_Array_Length_ReturnValue, float CallFunc_Array_Get_Item, bool CallFunc_Greater_IntInt_ReturnValue, float CallFunc_Array_Get_Item_1, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_CalcCaptureSuccessRate_successRate, double CallFunc_Multiply_DoubleDouble_ReturnValue_1, double CallFunc_Multiply_DoubleDouble_ReturnValue_2, TArray<double>& CallFunc_CalcCaptureSuccessRate_rateArray_ImplicitCast, double CallFunc_Multiply_DoubleDouble_B_ImplicitCast, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast);
	void On_Shake_Ball(class ABP_PalCaptureBodyBase_C* ShakedBody, TSoftObjectPtr<class ABP_PalCaptureBodyBase_C> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UWBP_PalGetReticle_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void UpdateSecondStepWidgetPosition(int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, TArray<TSoftObjectPtr<class ABP_PalCaptureBodyBase_C>>& CallFunc_Map_Keys_Keys, TSoftObjectPtr<class ABP_PalCaptureBodyBase_C> CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class ABP_PalCaptureBodyBase_C* K2Node_DynamicCast_AsBP_Pal_Capture_Body_Base, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, class UWBP_PalGetReticle_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void OnPassingJudge(int32 PhaseCount, class UPalIndividualCharacterHandle* TargetHandle, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, TArray<TSoftObjectPtr<class APalCharacter>>& CallFunc_Map_Keys_Keys, TSoftObjectPtr<class APalCharacter> CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Map_Remove_ReturnValue, class UWBP_CaptureFailedPercent_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, TArray<TSoftObjectPtr<class ABP_PalCaptureBodyBase_C>>& CallFunc_Map_Keys_Keys_1, int32 CallFunc_Array_Length_ReturnValue_1, TSoftObjectPtr<class ABP_PalCaptureBodyBase_C> CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_1, class ABP_PalCaptureBodyBase_C* K2Node_DynamicCast_AsBP_Pal_Capture_Body_Base, bool K2Node_DynamicCast_bSuccess_1, class UWBP_PalGetReticle_C* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, class UPalIndividualCharacterHandle* CallFunc_GetTargetHandle_targetHandle, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_IsValidSoftObjectReference_ReturnValue);
	void OnFailedCapture(class UPalIndividualCharacterHandle* TargetHandle, enum class EPalSphereCaptureFailedReason FailedReason, bool TmpValidHandle, bool IsAlreadyFailed, class UWBP_PalGetReticle_C* TmpRemoveReticle, const struct FVector& WorldLocation, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, TSoftObjectPtr<class APalCharacter> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable_1, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_1, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool K2Node_SwitchEnum_CmpSuccess, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, TArray<TSoftObjectPtr<class APalCharacter>>& CallFunc_Map_Keys_Keys, TSoftObjectPtr<class APalCharacter> CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, class UWBP_CaptureFailedPercent_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, class UWBP_CaptureFailedPercent_C* CallFunc_Create_ReturnValue, double CallFunc_Array_Get_Item_1, double CallFunc_Multiply_DoubleDouble_ReturnValue, class UPanelSlot* CallFunc_AddChild_ReturnValue, double CallFunc_MultiplyMultiply_FloatFloat_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue_1, TArray<TSoftObjectPtr<class ABP_PalCaptureBodyBase_C>>& CallFunc_Map_Keys_Keys_1, int32 CallFunc_Array_Length_ReturnValue_1, TSoftObjectPtr<class ABP_PalCaptureBodyBase_C> CallFunc_Array_Get_Item_2, bool CallFunc_Less_IntInt_ReturnValue_1, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_1, class ABP_PalCaptureBodyBase_C* K2Node_DynamicCast_AsBP_Pal_Capture_Body_Base, bool K2Node_DynamicCast_bSuccess_1, class UPalIndividualCharacterHandle* CallFunc_GetTargetHandle_targetHandle, bool CallFunc_Map_Remove_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, class UWBP_PalGetReticle_C* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, bool CallFunc_IsValidSoftObjectReference_ReturnValue);
	void OnSuccessedCapture(class UPalIndividualCharacterHandle* TargetHandle, int32 Temp_int_Array_Index_Variable, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Loop_Counter_Variable, TArray<TSoftObjectPtr<class ABP_PalCaptureBodyBase_C>>& CallFunc_Map_Keys_Keys, int32 CallFunc_Add_IntInt_ReturnValue, TSoftObjectPtr<class ABP_PalCaptureBodyBase_C> CallFunc_Array_Get_Item, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, bool CallFunc_Map_Remove_ReturnValue, class ABP_PalCaptureBodyBase_C* K2Node_DynamicCast_AsBP_Pal_Capture_Body_Base, bool K2Node_DynamicCast_bSuccess, class UWBP_PalGetReticle_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetTargetHandle_targetHandle, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_IsValidSoftObjectReference_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void OnStartedCapture(class AActor* CreatedBodyActor, class UPalIndividualCharacterHandle* TargetHandle, bool IsBonus, const TArray<float>& TmpRateArray, class UPalCharacterManager* CallFunc_GetCharacterManager_ReturnValue, class ABP_PalCaptureBodyBase_C* K2Node_DynamicCast_AsBP_Pal_Capture_Body_Base, bool K2Node_DynamicCast_bSuccess, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, TSoftObjectPtr<class ABP_PalCaptureBodyBase_C> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue, const struct FPalInstanceID& CallFunc_GetIndividualIDByActor_ReturnValue, TSoftObjectPtr<class ABP_PalCaptureBodyBase_C> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue_1, class UPalIndividualCharacterHandle* CallFunc_GetIndividualHandle_ReturnValue, int32 CallFunc_GetCaptureLevel_level, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_Map_Contains_ReturnValue, bool CallFunc_IsValid_ReturnValue, double CallFunc_CalcCaptureSuccessRate_successRate, int32 CallFunc_Array_Length_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class UPalGameSetting* CallFunc_GetGameSetting_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, float CallFunc_CalcCaptureRate_ReturnValue, TArray<float>& CallFunc_GetCalculatedCaptureRate_outCalculatedRateArray, float Temp_real_Variable, float CallFunc_Array_Get_Item, float CallFunc_Array_Get_Item_1, double CallFunc_Multiply_DoubleDouble_ReturnValue_1, double CallFunc_Multiply_DoubleDouble_ReturnValue_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_4, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, class UWBP_PalGetReticle_C* CallFunc_Create_ReturnValue, class UCanvasPanelSlot* CallFunc_AddChildToCanvas_ReturnValue, TArray<double>& CallFunc_SetCaptureRateList_rateList_ImplicitCast, TArray<double>& CallFunc_CalcCaptureSuccessRate_rateArray_ImplicitCast, double CallFunc_Multiply_DoubleDouble_B_ImplicitCast, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast, float CallFunc_Array_Set_Item_ImplicitCast);
	void OnThrowCaptureWeapon(class AActor* Bullet, bool CallFunc_IsValid_ReturnValue, class ABP_ThrowCaptureObjectBase_C* K2Node_DynamicCast_AsBP_Throw_Capture_Object_Base, bool K2Node_DynamicCast_bSuccess, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate);
	void RegisterWeaponEvent(class ABP_CapturePrism_C* NewWeapon, TSoftObjectPtr<class ABP_CapturePrism_C> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue, bool CallFunc_IsValid_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate);
	void UnregisterWeaponEvent(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_IsValidSoftObjectReference_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class ABP_ThrowWeaponBase_C* K2Node_DynamicCast_AsBP_Throw_Weapon_Base, bool K2Node_DynamicCast_bSuccess);
	void OnChangeWeapon(class APalWeaponBase* Weapon, bool CallFunc_IsValid_ReturnValue, class ABP_CapturePrism_C* K2Node_DynamicCast_AsBP_Capture_Prism, bool K2Node_DynamicCast_bSuccess, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, class APalPlayerController* K2Node_DynamicCast_AsPal_Player_Controller, bool K2Node_DynamicCast_bSuccess_1, class UPalLoadoutSelectorComponent* CallFunc_GetLoadoutSelectorComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, enum class EPalPlayerInventoryType CallFunc_GetPrimaryInventoryType_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue);
	void SetupAfterPlayerSpawned(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APalPlayerController* K2Node_DynamicCast_AsPal_Player_Controller, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_1);
	void ChangeSeqence(enum class EPalCaptureReticleSeqence NewSeqence, bool K2Node_SwitchEnum_CmpSuccess, bool K2Node_SwitchEnum_CmpSuccess_1, bool K2Node_SwitchEnum_CmpSuccess_2, bool K2Node_SwitchEnum_CmpSuccess_3);
	void FindTargetCharacter(class APalMonsterCharacter** TargetMonster, const TArray<class AActor*>& IgnoreActors, int32 Temp_int_Array_Index_Variable, bool CallFunc_ShouldReticleDIsplay_ShouldDisplay, int32 Temp_int_Loop_Counter_Variable, TArray<TSoftObjectPtr<class ABP_PalCaptureBodyBase_C>>& CallFunc_Map_Keys_Keys, int32 CallFunc_Add_IntInt_ReturnValue, TSoftObjectPtr<class ABP_PalCaptureBodyBase_C> CallFunc_Array_Get_Item, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, bool CallFunc_IsValidSoftObjectReference_ReturnValue, class ABP_PalCaptureBodyBase_C* K2Node_DynamicCast_AsBP_Pal_Capture_Body_Base, bool K2Node_DynamicCast_bSuccess, class UPalIndividualCharacterHandle* CallFunc_GetTargetHandle_targetHandle, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, const struct FRotator& CallFunc_GetCameraRotation_ReturnValue, const struct FVector& CallFunc_GetForwardVector_ReturnValue, const struct FVector& CallFunc_GetCameraLocation_ReturnValue, const struct FVector& CallFunc_Multiply_VectorFloat_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, const struct FHitResult& CallFunc_CapsuleTraceSingleForObjects_OutHit, bool CallFunc_CapsuleTraceSingleForObjects_ReturnValue, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, const struct FVector& CallFunc_BreakHitResult_Location, const struct FVector& CallFunc_BreakHitResult_ImpactPoint, const struct FVector& CallFunc_BreakHitResult_Normal, const struct FVector& CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class AActor* CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, class FName CallFunc_BreakHitResult_HitBoneName, class FName CallFunc_BreakHitResult_BoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_ElementIndex, int32 CallFunc_BreakHitResult_FaceIndex, const struct FVector& CallFunc_BreakHitResult_TraceStart, const struct FVector& CallFunc_BreakHitResult_TraceEnd, class APalMonsterCharacter* K2Node_DynamicCast_AsPal_Monster_Character, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_IsDead_ReturnValue, class UPalSkeletalMeshComponent* CallFunc_GetMainMesh_ReturnValue, bool CallFunc_IsVisible_ReturnValue, bool CallFunc_IsFriend_ReturnValue);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void OnInitialized();
	void OnSetup_AfterCreatedPlayer();
	void ExecuteUbergraph_WBP_CaptureReticle(int32 EntryPoint, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, bool CallFunc_IsValidSoftObjectReference_ReturnValue, class APalMonsterCharacter* K2Node_DynamicCast_AsPal_Monster_Character, bool K2Node_DynamicCast_bSuccess, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_1, bool CallFunc_IsValidSoftObjectReference_ReturnValue_1, class ABP_ThrowWeaponBase_C* K2Node_DynamicCast_AsBP_Throw_Weapon_Base, bool K2Node_DynamicCast_bSuccess_1, class ABP_CapturePrism_C* K2Node_DynamicCast_AsBP_Capture_Prism, bool K2Node_DynamicCast_bSuccess_2, class ABP_CapturePrism_C* K2Node_DynamicCast_AsBP_Capture_Prism_1, bool K2Node_DynamicCast_bSuccess_3, bool CallFunc_Greater_DoubleDouble_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsBonusEnabled_enabled, class APalMonsterCharacter* CallFunc_FindTargetCharacter_targetMonster, bool CallFunc_NotEqual_BoolBool_ReturnValue, TSoftObjectPtr<class APalMonsterCharacter> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue, double CallFunc_Get_Display_Rate_rate, bool CallFunc_Get_Display_Rate_isSneakBonus, class UPalCharacterParameterComponent* CallFunc_GetCharacterParameterComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue, enum class EPalTribeID CallFunc_GetTribeID_ReturnValue, double CallFunc_Get_Display_Rate_rate_1, bool CallFunc_Get_Display_Rate_isSneakBonus_1, bool CallFunc_NotEqual_ObjectObject_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, double CallFunc_Add_DoubleDouble_ReturnValue, class UPalPlayerRecordData* CallFunc_GetLocalRecordData_ReturnValue, int32 CallFunc_GetRecordData_TribeIdCount_ReturnValue, int64 CallFunc_Conv_IntToInt64_ReturnValue, bool CallFunc_Greater_Int64Int64_ReturnValue, double CallFunc_UpdateFailedWidgets_DeltaTime_ImplicitCast, double CallFunc_Add_DoubleDouble_B_ImplicitCast);
};

}


