#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x270 (0x4F0 - 0x280)
// WidgetBlueprintGeneratedClass WBP_Ingame_PlayerGauge_Separated.WBP_Ingame_PlayerGauge_Separated_C
class UWBP_Ingame_PlayerGauge_Separated_C : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x280(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                      Anm_HP_Gauge_Default;                              // 0x288(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_HP_Gauge_Low;                                  // 0x290(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_Weapon_Broken;                                 // 0x298(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_Weapon_Default;                                // 0x2A0(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_ShowHideRight;                                 // 0x2A8(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_ShowHideLeft;                                  // 0x2B0(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_UseBullet;                                     // 0x2B8(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_Damage;                                        // 0x2C0(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_HPGaugeFlare_Yellow;                           // 0x2C8(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_HPGaugeFlare_Blue;                             // 0x2D0(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_ShieldGaugeFlare_Color_Yellow;                 // 0x2D8(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                      Anm_ShieldGaugeFlare_Color_Blue;                   // 0x2E0(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                          Canvas_Shield;                                     // 0x2E8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                          Canvas_WeaponInfo;                                 // 0x2F0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                          CanvasPanel_GrapplingGun_Cool;                     // 0x2F8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                        HorizontalBox_BallChangeKeyGuide;                  // 0x300(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                        HorizontalBox_BallChangeKeyGuide_1;                // 0x308(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                        HorizontalBox_SphereNum;                           // 0x310(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Icon_Weapon;                                       // 0x318(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_Infinity;                                    // 0x320(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_Sphere;                                      // 0x328(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                          ProgressBar_CoolProgress;                          // 0x330(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                          ProgressBar_HPGauge;                               // 0x338(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                          ProgressBar_HPGauge_Back;                          // 0x340(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                          ProgressBar_ShieldGauge;                           // 0x348(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                          ProgressBar_ShieldGauge_Back;                      // 0x350(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_CoolTimerNum;                                 // 0x358(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_MaxBulletNum;                                 // 0x360(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_MaxHP;                                        // 0x368(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_NowBulletNum;                                 // 0x370(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_NowHP;                                        // 0x378(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_SphereName;                                   // 0x380(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_SphereNum_1;                                  // 0x388(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_SphereNum_10;                                 // 0x390(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_SphereNum_100;                                // 0x398(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_SphereNum_Plus;                               // 0x3A0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                    Text_WeaponName;                                   // 0x3A8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          VerticalBox_BulletNum;                             // 0x3B0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Ingame_PalHPGauge_C*              WBP_Ingame_PalHPGauge;                             // 0x3B8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Ingame_PlayerGauge_KeyGuide_C*    WBP_Ingame_PlayerGauge_KeyGuide_PalInstruct;       // 0x3C0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Ingame_PlayerGauge_KeyGuide_C*    WBP_Ingame_PlayerGauge_KeyGuide_SummonPal;         // 0x3C8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Ingame_PlayerGauge_KeyGuide_C*    WBP_Ingame_PlayerGauge_KeyGuide_ThrowSphere;       // 0x3D0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Ingame_PlayerGauge_ThworObjectNone_C* WBP_Ingame_PlayerGauge_PalSphereNone;              // 0x3D8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Ingame_Thermometer_C*             WBP_Ingame_Thermometer;                            // 0x3E0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Ingame_TimeZone_C*                WBP_Ingame_TimeZone;                               // 0x3E8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_IngameHungerGauge_C*              WBP_IngameHungerGauge;                             // 0x3F0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_IngameStatusPoint_C*              WBP_IngameStatusPoint;                             // 0x3F8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PlayerInputKeyGuideIcon_C*        WBP_PlayerInputKeyGuideIcon_ChangeBallAiming;      // 0x400(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PlayerInputKeyGuideIcon_C*        WBP_PlayerInputKeyGuideIcon_ChangeBallAiming_1;    // 0x408(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PlayerInputKeyGuideIcon_C*        WBP_PlayerInputKeyGuideIcon_ChangeBallStatic;      // 0x410(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPalUIDelayGaugeCalculator*            HpDelayGauge;                                      // 0x418(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UPalUIDelayGaugeCalculator*            ShieldDelayGauge;                                  // 0x420(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class APalWeaponBase>         NowHasWeapon;                                      // 0x428(0x30)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                        LasMaxBulletNum;                                   // 0x458(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        LastNowBulletNum;                                  // 0x45C(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        SavedMagazineSize;                                 // 0x460(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2CD2[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UMaterialInstanceDynamic*              bulletGaugeMaterial;                               // 0x468(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FFixedPoint64                         LastShield;                                        // 0x470(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                         IsRiding;                                          // 0x478(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2CD5[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class FName                                  CachedLastEquipBallID;                             // 0x47C(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2CD6[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TMap<struct FPalDataTableRowName_ItemData, TSoftObjectPtr<class UTexture2D>> BallIconMap;                                       // 0x488(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FTimerHandle                          HideBallnameTimerHandle;                           // 0x4D8(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                         IsOverBallNameHideTimer;                           // 0x4E0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         IsAiming;                                          // 0x4E1(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         HasSpecialWeapon;                                  // 0x4E2(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         IsNothingBall;                                     // 0x4E3(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         IsFirstUpdateHP;                                   // 0x4E4(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2CD9[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UPalItemSlot*                          CurrentGrenadeSlot;                                // 0x4E8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UWBP_Ingame_PlayerGauge_Separated_C* GetDefaultObj();

	void CREATEDELEGATE_PROXYFUNCTION_1(float RemainingTime, float CoolDownTime, double CallFunc_OnGrapplingGunCoolTimerUpdate_Timer_ImplicitCast, double CallFunc_OnGrapplingGunCoolTimerUpdate_CoolTime_ImplicitCast);
	void CREATEDELEGATE_PROXYFUNCTION_0(float RemainingTime, float CoolDownTime, double CallFunc_OnGrapplingGunCoolTimerUpdate_Timer_ImplicitCast, double CallFunc_OnGrapplingGunCoolTimerUpdate_CoolTime_ImplicitCast);
	void SetEnableFirstSummonPalGuide(bool IsEnableFlag);
	void SetWeaponNameText(class APalWeaponBase* WeaponBase, bool CallFunc_IsPalThrowWeapon_isPalThrowWeapon, const struct FPalItemId& CallFunc_GetItemId_ReturnValue, class FText CallFunc_GetItemName_outName, bool CallFunc_NotEqual_NameName_ReturnValue);
	void OnGrapplingGunCoolStateUpdate(bool StartCool, bool Temp_bool_Variable, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, enum class ESlateVisibility K2Node_Select_Default);
	void OnGrapplingGunCoolTimerUpdate(double Timer, double CoolTime, double CallFunc_Divide_DoubleDouble_ReturnValue, int32 CallFunc_Round_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue, float CallFunc_SetPercent_InPercent_ImplicitCast);
	void SetUsableHandFlag(bool IsLeftHandUsable, bool IsRightHandUsable, double CallFunc_SelectFloat_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, class UPalShooterComponent* CallFunc_GetComponentByClass_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class APalWeaponBase* K2Node_DynamicCast_AsPal_Weapon_Base, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValidSoftObjectReference_ReturnValue, bool CallFunc_CanUseWeapon_ReturnValue, double CallFunc_SelectFloat_ReturnValue_1, float CallFunc_SetRenderOpacity_InOpacity_ImplicitCast, float CallFunc_SetRenderOpacity_InOpacity_ImplicitCast_1);
	void SetBallNum(int32 Num, bool Temp_bool_Variable, bool CallFunc_GreaterEqual_IntInt_ReturnValue, int32 CallFunc_Min_ReturnValue, TSubclassOf<class UCommonTextStyle> Temp_class_Variable, int32 CallFunc_Max_ReturnValue, int32 CallFunc_Divide_IntInt_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 CallFunc_Divide_IntInt_ReturnValue_1, int32 CallFunc_Percent_IntInt_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, class FText CallFunc_Conv_IntToText_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, class FText CallFunc_Conv_IntToText_ReturnValue_2, TSubclassOf<class UCommonTextStyle> Temp_class_Variable_1, bool Temp_bool_Variable_1, TSubclassOf<class UCommonTextStyle> K2Node_Select_Default, TSubclassOf<class UCommonTextStyle> Temp_class_Variable_2, TSubclassOf<class UCommonTextStyle> Temp_class_Variable_3, bool Temp_bool_Variable_2, TSubclassOf<class UCommonTextStyle> K2Node_Select_Default_1, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, enum class ESlateVisibility K2Node_Select_Default_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, TSubclassOf<class UCommonTextStyle> Temp_class_Variable_4, TSubclassOf<class UCommonTextStyle> Temp_class_Variable_5, bool Temp_bool_Variable_3, TSubclassOf<class UCommonTextStyle> K2Node_Select_Default_3);
	void HideBallName();
	void SetBallDetail(class FName BallItemID, int32 DisplayNum, bool CallFunc_EqualEqual_IntInt_ReturnValue, const struct FPalDataTableRowName_ItemData& K2Node_MakeStruct_PalDataTableRowName_ItemData, class FText CallFunc_GetItemName_outName, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, const struct FTimerHandle& CallFunc_K2_SetTimerDelegate_ReturnValue, TSoftObjectPtr<class UTexture2D> CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void Set_Player_Hunger(double HungerRate);
	void SetVisibilityShield(bool IsVisible, uint8 CallFunc_MakeLiteralByte_ReturnValue, bool Temp_bool_Variable, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility K2Node_Select_Default);
	void OnUpdateGrenadeLoadoutSlot(class UPalItemSlot* Slot, int32 CallFunc_GetStackCount_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void OnUpdateBallLoadoutSlot(class UPalItemSlot* Slot, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetStackCount_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue);
	void RegisterBallLoadoutEvent(class UPalItemSlot* ItemSlot, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate);
	void IsRideCharacterSPFull();
	void ChangeNoRideMode();
	void ChangeRideMode(class AActor* Actor);
	void OnEndShieldGaugeDelay(int64 CallFunc_Convert_FixedPoint64ToInt64_ReturnValue, bool CallFunc_EqualEqual_Int64Int64_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue);
	void OnStartShieldGaugeDelay(class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue);
	void OnEndHPGaugeDelay(class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue);
	void OnStartHPGaugeDelay(class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue);
	void Setup_Delay_Gauge(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, class UPalUIDelayGaugeCalculator* CallFunc_SpawnObject_ReturnValue, class UPalUIDelayGaugeCalculator* CallFunc_SpawnObject_ReturnValue_1);
	void IsPalThrowWeapon(class APalWeaponBase* WeaponBase, bool* IsPalThrowWeapon, class ABP_ThrowPalWeapon_C* K2Node_DynamicCast_AsBP_Throw_Pal_Weapon, bool K2Node_DynamicCast_bSuccess);
	void IsSpecialWeapon(class APalWeaponBase* WeaponBase, bool* IsSpecial, const struct FPalItemId& CallFunc_GetItemId_ReturnValue, class UPalItemIDManager* CallFunc_GetItemIDManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UPalStaticItemDataBase* CallFunc_GetStaticItemData_ReturnValue, class UPalStaticWeaponItemData* K2Node_DynamicCast_AsPal_Static_Weapon_Item_Data, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue);
	void IsDummyWeapon(class APalWeaponBase* WeaponBase, bool* IsDummy, class ABP_ThrowWeapon_Dummy_C* K2Node_DynamicCast_AsBP_Throw_Weapon_Dummy, bool K2Node_DynamicCast_bSuccess);
	void Is_Require_Bullet(class APalWeaponBase* WeaponActor, bool* IsRequire, bool CallFunc_IsValid_ReturnValue, class FName CallFunc_GetRequiredBulletName_outName, bool CallFunc_NotEqual_NameName_ReturnValue);
	void TryUpdateMaxBullet(int32 CallFunc_CalcMaxBulletNum_maxBulletNum, bool CallFunc_IsValidSoftObjectReference_ReturnValue);
	void UpdatePalInfo(class UPalIndividualCharacterSlot* TargetSlot);
	void IsInfinityWeapon(class FName WeaponName, bool* IsInfinity, class UPalItemIDManager* CallFunc_GetItemIDManager_ReturnValue, class UPalStaticItemDataBase* CallFunc_GetStaticItemData_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UPalStaticWeaponItemData* K2Node_DynamicCast_AsPal_Static_Weapon_Item_Data, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue);
	void HideBulletInfo();
	void HideAllWeaponInfo();
	void ChangePalThrowDetail(class UPalOtomoHolderComponentBase* CallFunc_GetOtomoHolderComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetSelectedOtomoID_ReturnValue, class UPalIndividualCharacterSlot* CallFunc_GetOtomoIndividualCharacterSlot_ReturnValue);
	void Change_Normal_Weapon_Detail(bool IsGrenade, bool Temp_bool_Variable, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, enum class ESlateVisibility K2Node_Select_Default);
	void Change_Infinity_Weapon_Detail(class APalWeaponBase* WeaponBase, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue);
	void Update_Weapon_Icon(class APalWeaponBase* WeaponBase, bool CallFunc_IsPalThrowWeapon_isPalThrowWeapon, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValidSoftObjectReference_ReturnValue, bool CallFunc_IsSpecialWeapon_isSpecial);
	void OnReloadWeapon(int32 bulletsNum, int32 CallFunc_CalcMaxBulletNum_maxBulletNum);
	void CalcMaxBulletNum(int32* MaxBulletNum, class UPalPlayerInventoryData* CallFunc_GetLocalInventoryData_ReturnValue, bool CallFunc_IsValidSoftObjectReference_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class APalWeaponBase* K2Node_DynamicCast_AsPal_Weapon_Base, bool K2Node_DynamicCast_bSuccess, class FName CallFunc_GetRequiredBulletName_outName, bool CallFunc_IsValid_ReturnValue, bool CallFunc_NotEqual_NameName_ReturnValue, int32 CallFunc_CountItemNum_ReturnValue);
	void UpdateMaxBulletNum(int32 MaxBulletNum, TSubclassOf<class UCommonTextStyle> Temp_class_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, TSubclassOf<class UCommonTextStyle> Temp_class_Variable_1, bool Temp_bool_Variable, TSubclassOf<class UCommonTextStyle> K2Node_Select_Default, bool CallFunc_Greater_IntInt_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue);
	void Update_Now_Bullet_Num(int32 NowBulletNum, TSubclassOf<class UCommonTextStyle> Temp_class_Variable, TSubclassOf<class UCommonTextStyle> Temp_class_Variable_1, bool Temp_bool_Variable, bool CallFunc_NotEqual_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue, TSubclassOf<class UCommonTextStyle> K2Node_Select_Default);
	void SetupBulletGauge(int32 MagazineSize, float CallFunc_Conv_IntToFloat_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void Setup_Bullet_Info(class APalWeaponBase* WeaponBase, class ABP_ThrowWeapon_GrenadeBase_C* K2Node_DynamicCast_AsBP_Throw_Weapon_Grenade_Base, bool K2Node_DynamicCast_bSuccess, const struct FPalItemId& CallFunc_GetItemId_ReturnValue, bool CallFunc_IsPalThrowWeapon_isPalThrowWeapon, bool CallFunc_IsInfinityWeapon_isInfinity, bool CallFunc_Is_Require_Bullet_IsRequire, int32 CallFunc_CalcMaxBulletNum_maxBulletNum, int32 CallFunc_GetRemainBulletCount_ReturnValue, int32 CallFunc_GetMagazineSize_ReturnValue);
	void BindWeaponEvent(class APalWeaponBase* WeaponBase, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class ABP_GrapplingGun_C* K2Node_DynamicCast_AsBP_Grappling_Gun, bool K2Node_DynamicCast_bSuccess, class ABP_ThrowWeapon_GrenadeBase_C* K2Node_DynamicCast_AsBP_Throw_Weapon_Grenade_Base, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_IsCoolDown_ReturnValue, float CallFunc_GetRemainingCoolDownTime_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, class UPalPlayerInventoryData* CallFunc_GetLocalInventoryData_ReturnValue, class UPalItemContainer* CallFunc_TryGetContainerFromInventoryType_outContainer, bool CallFunc_TryGetContainerFromInventoryType_ReturnValue, int32 CallFunc_GetNowSelectedIndex_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, class UPalItemSlot* CallFunc_Array_Get_Item, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_4, double CallFunc_OnGrapplingGunCoolTimerUpdate_Timer_ImplicitCast, double CallFunc_OnGrapplingGunCoolTimerUpdate_CoolTime_ImplicitCast);
	void UnbindLastEquipedWeaponEvent(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, bool CallFunc_IsValid_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_4, bool CallFunc_IsValidSoftObjectReference_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class APalWeaponBase* K2Node_DynamicCast_AsPal_Weapon_Base, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue_1, class ABP_GrapplingGun_C* K2Node_DynamicCast_AsBP_Grappling_Gun, bool K2Node_DynamicCast_bSuccess_1, class ABP_ThrowWeapon_GrenadeBase_C* K2Node_DynamicCast_AsBP_Throw_Weapon_Grenade_Base, bool K2Node_DynamicCast_bSuccess_2);
	void Update_Weapon(class APalWeaponBase* WeaponBase, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsDummyWeapon_IsDummy, bool CallFunc_IsSpecialWeapon_isSpecial, class UPalOtomoHolderComponentBase* CallFunc_GetOtomoHolderComponent_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_IsALLEmpty_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue_1, enum class EPalPlayerInventoryType CallFunc_GetPrimaryInventoryType_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue, class UPalShooterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_CanUseRightHand_ReturnValue, bool CallFunc_CanUseLeftHand_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, enum class EPalPlayerInventoryType CallFunc_GetPrimaryInventoryType_ReturnValue_1, bool CallFunc_NotEqual_ByteByte_ReturnValue, TSoftObjectPtr<class APalWeaponBase> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_IsValidSoftObjectReference_ReturnValue);
	void UpdateShield(const struct FFixedPoint64& MaxShield, const struct FFixedPoint64& NowShield, bool CallFunc_EqualEqual_FixedPoint64FixedPoint64_ReturnValue, float CallFunc_Convert_FixedPoint64ToFloat_ReturnValue, float CallFunc_Convert_FixedPoint64ToFloat_ReturnValue_1, bool CallFunc_EqualEqual_DoubleDouble_ReturnValue, int64 CallFunc_Convert_FixedPoint64ToInt64_ReturnValue, bool CallFunc_EqualEqual_Int64Int64_ReturnValue, double CallFunc_Divide_DoubleDouble_ReturnValue, double CallFunc_Divide_DoubleDouble_A_ImplicitCast, double CallFunc_Divide_DoubleDouble_B_ImplicitCast, double CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast, float CallFunc_SetPercent_percent_ImplicitCast);
	void UpdateSP(const struct FFixedPoint64& NowSP, const struct FFixedPoint64& MaxSP, bool IsOverHeated);
	void UpdateHP(const struct FFixedPoint64& NowHP, const struct FFixedPoint64& MaxHP, float CallFunc_Convert_FixedPoint64ToFloat_ReturnValue, int64 CallFunc_Convert_FixedPoint64ToInt64_ReturnValue, float CallFunc_Convert_FixedPoint64ToFloat_ReturnValue_1, class FText CallFunc_Conv_Int64ToText_ReturnValue, double CallFunc_Divide_DoubleDouble_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, int64 CallFunc_Convert_FixedPoint64ToInt64_ReturnValue_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Conv_Int64ToText_ReturnValue_1, class FText CallFunc_Format_ReturnValue, double CallFunc_Divide_DoubleDouble_B_ImplicitCast, double CallFunc_Divide_DoubleDouble_A_ImplicitCast, float CallFunc_SetPercent_percent_ImplicitCast, float CallFunc_SetPercentForce_percent_ImplicitCast);
	void AnmEvent_TriggerDamage();
	void AnmEvent_UseBullet();
	void AnmEvent_ShowHideLeft(bool Hide);
	void AnmEvent_ShowHideRight(bool Hide);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void OnInitialized();
	void ExecuteUbergraph_WBP_Ingame_PlayerGauge_Separated(int32 EntryPoint, enum class EUMGSequencePlayMode Temp_byte_Variable, enum class EUMGSequencePlayMode Temp_byte_Variable_1, bool Temp_bool_Variable, enum class EUMGSequencePlayMode Temp_byte_Variable_2, enum class EUMGSequencePlayMode Temp_byte_Variable_3, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, bool K2Node_CustomEvent_Hide_1, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_1, bool K2Node_CustomEvent_Hide, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, enum class EUMGSequencePlayMode K2Node_Select_Default, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_2, bool Temp_bool_Variable_1, enum class EUMGSequencePlayMode K2Node_Select_Default_1, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue_3);
};

}


