#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x164 (0x58C - 0x428)
// WidgetBlueprintGeneratedClass WBP_PalNPCHPGaugeCanvas.WBP_PalNPCHPGaugeCanvas_C
class UWBP_PalNPCHPGaugeCanvas_C : public UPalUINPCHPGaugeCanvasBase
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x428(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                      Default_In;                                        // 0x430(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                          Canvas_Root;                                       // 0x438(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          VerticalBox_60;                                    // 0x440(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMap<class APalCharacter*, class UWBP_PalNPCHPGauge_C*> DisplayedPalGaugeMap;                              // 0x448(0x50)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, ContainsInstancedReference)
	TMap<class APalCharacter*, class UPalUICharacterHPGaugeBase*> DisplayedBossUGaugeMap;                            // 0x498(0x50)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, ContainsInstancedReference)
	TMap<class APalCharacter*, class UWBP_PlayerHPGauge_C*> DisplayedPlayerGaugeMap;                           // 0x4E8(0x50)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, ContainsInstancedReference)
	double                                       DisplayGaugeDistance;                              // 0x538(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       HideTimer;                                         // 0x540(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       HideTime;                                          // 0x548(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       DisplayGaugeRange_Sight;                           // 0x550(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         IsOverHideTime;                                    // 0x558(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         IsConflicted;                                      // 0x559(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_B54[0x6];                                      // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<class UBP_UIIndividualParameterInitializeWaiter_C*> InitializeWaiters;                                 // 0x560(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FTimerHandle                          UpdateTimerHandle;                                 // 0x570(0x8)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                       DelayCloseGauges;                                  // 0x578(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	float                                        DisplayGaugeDistance_SameGuildPlayer;              // 0x588(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UWBP_PalNPCHPGaugeCanvas_C* GetDefaultObj();

	void CREATEDELEGATE_PROXYFUNCTION_0(struct FPalDamageInfo& DamageInfo, class AActor* Defender);
	void CloseDelayGauges(class UWidget* Widget, bool CallFunc_Array_RemoveItem_ReturnValue);
	void SetGaugeVisibility(class UWidget* Widget, class AActor* TargetActor, bool DelayClose, bool Close, double CallFunc_GetDistanceByPlayer_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, bool CallFunc_Array_RemoveItem_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Array_Contains_ReturnValue_1, class UWBP_PlayerHPGauge_C* K2Node_DynamicCast_AsWBP_Player_HPGauge, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Add_ReturnValue, class UWBP_PalNPCHPGauge_C* K2Node_DynamicCast_AsWBP_Pal_NPCHPGauge, bool K2Node_DynamicCast_bSuccess_1);
	void OnDamagePopup(const struct FPalDamageInfo& DamageInfo, class AActor* Actor, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, class UWBP_PlayerHPGauge_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UWBP_PalNPCHPGauge_C* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1);
	void Update_Visibility_Player_Gauges(const TArray<struct FHitResult>& TraceResult, class UWBP_PlayerHPGauge_C* TmpNowProcessingWidget, class APalCharacter* TmpNowProcessingCharacter, int32 Temp_int_Array_Index_Variable, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_IsFriend_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Is_Sight_Display_Return, double CallFunc_GetDistanceByPlayer_ReturnValue, bool CallFunc_IsDisplayDistance_isDisplay, TArray<class APalCharacter*>& CallFunc_Map_Keys_Keys, class UPalDebugSetting* CallFunc_GetPalDebugSetting_ReturnValue, class APalCharacter* CallFunc_Array_Get_Item, bool CallFunc_IsValid_ReturnValue, class UWBP_PlayerHPGauge_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsDying_ReturnValue, bool CallFunc_IsDead_ReturnValue, bool CallFunc_GetActorEnableCollision_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanOR_ReturnValue);
	void Setup(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UPalDamagePopUpManager* CallFunc_GetDamagePopUpManager_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, class USphereComponent* CallFunc_AddComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UPalGameSetting* CallFunc_GetGameSetting_ReturnValue, const struct FTimerHandle& CallFunc_K2_SetTimerDelegate_ReturnValue, float CallFunc_SetSphereRadius_InSphereRadius_ImplicitCast, double K2Node_VariableSet_DisplayGaugeDistance_ImplicitCast, double K2Node_VariableSet_DisplayGaugeRange_Sight_ImplicitCast);
	void OnEndPlayer(class AActor* Actor, enum class EEndPlayReason EndPlayReason, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_Map_Remove_ReturnValue, class UWBP_PlayerHPGauge_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void OnEndPlayBossPal(class AActor* Actor, enum class EEndPlayReason EndPlayReason, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_Map_Remove_ReturnValue, class UPalUICharacterHPGaugeBase* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void OnEndPlayNormalPal(class AActor* Actor, enum class EEndPlayReason EndPlayReason, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Map_Remove_ReturnValue, class UWBP_PalNPCHPGauge_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void UpdateVisibility_BossGauge(class APalCharacter* NowWorkBossCharacter, int32 Temp_int_Array_Index_Variable, bool CallFunc_IsValid_ReturnValue, const struct FFixedPoint64& CallFunc_GetMaxHP_ReturnValue, const struct FFixedPoint64& CallFunc_GetHP_ReturnValue, class UPalSkeletalMeshComponent* CallFunc_GetMainMesh_ReturnValue, bool CallFunc_Less_FixedPoint64FixedPoint64_ReturnValue, bool CallFunc_IsVisible_ReturnValue, bool CallFunc_Is_Sight_Display_Return, bool CallFunc_GetBattleMode_ReturnValue, int32 Temp_int_Loop_Counter_Variable, class UPalUICharacterHPGaugeBase* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, TArray<class APalCharacter*>& CallFunc_Map_Keys_Keys, class APalCharacter* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void Update_Children_Timer();
	void Is_Sight_Display(class APalCharacter* Actor, bool* Return, const struct FVector& TmpLocation, double DotST, class UPalFlyMeshHeightCtrlComponent* CallFunc_GetComponentByClass_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsValid_ReturnValue, float CallFunc_GetDefaultMeshLocationZ_ReturnValue, bool CallFunc_IsFlying_ReturnValue, const struct FVector& CallFunc_GetCameraLocationAndForwardVector_location, const struct FVector& CallFunc_GetCameraLocationAndForwardVector_forwardVector, class UPalSkeletalMeshComponent* CallFunc_GetMainMesh_ReturnValue, class UPalInteractableSphereComponentNative* CallFunc_GetComponentByClass_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, double CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double CallFunc_BreakVector_Z, double CallFunc_Subtract_DoubleDouble_ReturnValue, float CallFunc_GetScaledSphereRadius_ReturnValue, const struct FVector& CallFunc_MakeVector_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_1, double CallFunc_FMin_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue_1, TArray<class AActor*>& Temp_object_Variable, const struct FVector& CallFunc_GetCameraLocationAndForwardVector_location_1, const struct FVector& CallFunc_GetCameraLocationAndForwardVector_forwardVector_1, const struct FHitResult& CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, const struct FVector& CallFunc_Normal_ReturnValue, double CallFunc_Dot_VectorVector_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_B_ImplicitCast, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast);
	void IsDisplayDistance(double Distance, bool IsSameGuild, bool* IsDisplay, double CallFunc_SelectFloat_ReturnValue, bool CallFunc_LessEqual_DoubleDouble_ReturnValue, double CallFunc_SelectFloat_A_ImplicitCast);
	void Update_Visibility_Pal_HPGauges(bool InSight, double TmpDistance_PalHpGauge, const TArray<struct FHitResult>& TraceResult, class UWBP_PalNPCHPGauge_C* TmpNowProcessingWidget, class APalCharacter* TmpNowProcessingCharacter, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Is_Sight_Display_Return, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, bool CallFunc_GetBattleMode_ReturnValue, bool CallFunc_IsDead_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_GetActorEnableCollision_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue, class APalPlayerCharacter* CallFunc_GetTrainerPlayer_ReturnValue, double CallFunc_GetDistanceByPlayer_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsDisplayDistance_isDisplay, class UPalDebugSetting* CallFunc_GetPalDebugSetting_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, TArray<class APalCharacter*>& CallFunc_Map_Keys_Keys, class UWBP_PalNPCHPGauge_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class APalCharacter* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void OnBossDead(class APalCharacter* TargetCharacter, bool CallFunc_IsValid_ReturnValue, class UPalUICharacterHPGaugeBase* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void OnInitializedCharacter(class APalCharacter* TargetCharacter, class UBP_UIIndividualParameterInitializeWaiter_C* SelfObject, bool CallFunc_Array_RemoveItem_ReturnValue);
	void OnEndOverlap(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void GetCameraLocationAndForwardVector(struct FVector* Location, struct FVector* ForwardVector, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, const struct FRotator& CallFunc_GetCameraRotation_ReturnValue, const struct FVector& CallFunc_GetCameraLocation_ReturnValue, const struct FVector& CallFunc_GetForwardVector_ReturnValue, const struct FVector& CallFunc_Normal_ReturnValue);
	void IsAiming(bool* IsAiming, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsAiming_ReturnValue);
	void OnBeginOverlap(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, struct FHitResult& SweepResult, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_NotEqual_ObjectObject_ReturnValue, bool CallFunc_IsInitialized_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UBP_UIIndividualParameterInitializeWaiter_C* CallFunc_SpawnObject_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void Add_Player_Gauge(class APalCharacter* TargetCharacter, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetIndividualCharacterHandleByActor_ReturnValue, class UWBP_PlayerHPGauge_C* CallFunc_Create_ReturnValue, class UCanvasPanelSlot* CallFunc_AddChildToCanvas_ReturnValue);
	void AddNormalPalGauge(class APalCharacter* TargetCharacter, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class UPalCharacterParameterComponent* CallFunc_GetCharacterParameterComponent_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UWBP_PalNPCHPGauge_C* CallFunc_Create_ReturnValue, class UPanelSlot* CallFunc_AddChild_ReturnValue);
	void AddBossGauge(class APalCharacter* TargetCharacter, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UWBP_BossEnemyHPGauge_C* CallFunc_Create_ReturnValue, class UPanelSlot* CallFunc_AddChild_ReturnValue);
	void UpdateChildren_ForTick(double DeltaTime, const struct FHitResult& NewLocalVar_1, bool NewLocalVar_0, double Distance, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, TArray<class UWBP_PlayerHPGauge_C*>& CallFunc_Map_Values_Values, int32 CallFunc_Add_IntInt_ReturnValue_1, class UWBP_PlayerHPGauge_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, TArray<class UWBP_PalNPCHPGauge_C*>& CallFunc_Map_Values_Values_1, int32 CallFunc_Array_Length_ReturnValue_1, class UWBP_PalNPCHPGauge_C* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	void IsConflict(bool* IsConflict, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, bool CallFunc_GetBattleMode_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void Remove_Children(int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_1, TArray<class APalCharacter*>& CallFunc_Map_Keys_Keys, double CallFunc_Multiply_DoubleDouble_ReturnValue, class APalCharacter* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class FText CallFunc_Conv_ObjectToText_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, bool CallFunc_Map_Remove_ReturnValue, class FText CallFunc_Format_ReturnValue, class UPalUICharacterHPGaugeBase* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue, bool CallFunc_IsValid_ReturnValue, double CallFunc_GetDistanceByPlayer_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, TArray<class APalCharacter*>& CallFunc_Map_Keys_Keys_1, double CallFunc_Multiply_DoubleDouble_ReturnValue_1, class APalCharacter* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, class FText CallFunc_Conv_ObjectToText_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_1, class FText CallFunc_Format_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, double CallFunc_GetDistanceByPlayer_ReturnValue_1, bool CallFunc_Greater_DoubleDouble_ReturnValue_1, bool CallFunc_Map_Remove_ReturnValue_1, class UWBP_PalNPCHPGauge_C* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1);
	void Add_New_Gauge_UI(class APalCharacter* TargetCharacter, class APalPlayerState* CallFunc_GetLocalPlayerState_ReturnValue, class UPalDatabaseCharacterParameter* CallFunc_GetDatabaseCharacterParameter_ReturnValue, class UPalPlayerLocalRecordData* CallFunc_GetLocalRecordData_ReturnValue, bool Temp_bool_Variable, class UPalCharacterParameterComponent* CallFunc_GetCharacterParameterComponent_ReturnValue, class UPalIndividualCharacterParameter* CallFunc_TryGetIndividualParameter_ReturnValue, const struct FPalIndividualCharacterSaveParameter& CallFunc_GetSaveParameter_ReturnValue, bool Temp_bool_Variable_1, class UPalCharacterParameterComponent* CallFunc_GetCharacterParameterComponent_ReturnValue_1, class UPalIndividualCharacterParameter* CallFunc_TryGetIndividualParameter_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, enum class EPalTribeID CallFunc_GetTribeID_ReturnValue, bool CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class FName CallFunc_GetCharacterID_ReturnValue, bool CallFunc_GetIsPal_ReturnValue, const struct FPalIndividualCharacterSaveParameter& CallFunc_GetSaveParameter_ReturnValue_1, bool CallFunc_IsRarePal_ReturnValue, bool CallFunc_IsValid_Guid_ReturnValue, bool CallFunc_IsBossPal_Database_ReturnValue, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, bool CallFunc_IsFriend_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void IsDisplayGaugeByPlayerRotation(class APalCharacter* TargetCharacter, bool* IsDisplay, bool CallFunc_IsValid_ReturnValue, double CallFunc_GetDistanceByPlayer_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue, bool CallFunc_GetActiveActorFlag_ReturnValue, double CallFunc_GetDistanceByPlayer_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue_1, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, const struct FVector& CallFunc_GetCameraLocation_ReturnValue, const struct FRotator& CallFunc_GetCameraRotation_ReturnValue, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, const struct FVector& CallFunc_GetForwardVector_ReturnValue, const struct FVector& CallFunc_Normal_ReturnValue, double CallFunc_Dot_VectorVector_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue);
	void Try_Process_DIsplay_Gauge(class APalCharacter* TargetCharacter, class UWBP_PlayerHPGauge_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_IsDead_ReturnValue, class UPalUICharacterHPGaugeBase* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, class UWBP_PalNPCHPGauge_C* CallFunc_Map_Find_Value_2, bool CallFunc_Map_Find_ReturnValue_2);
	double GetDistanceByPlayer(class AActor* TargetActor, class APalPlayerCharacter* CallFunc_GetPalmi_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue_1, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, double CallFunc_VSize_ReturnValue);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Destruct();
	void ExecuteUbergraph_WBP_PalNPCHPGaugeCanvas(int32 EntryPoint, bool CallFunc_IsConflict_isConflict, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, double CallFunc_Add_DoubleDouble_ReturnValue, bool CallFunc_GreaterEqual_DoubleDouble_ReturnValue, bool CallFunc_IsAiming_IsAiming, double CallFunc_Add_DoubleDouble_B_ImplicitCast, double CallFunc_UpdateChildren_ForTick_deltaTime_ImplicitCast);
};

}


